### ISSUE TITLE
[Bug] cannot import name '__version__' from 'weaviate'

### ISSUE THREAD

**Issue by PylotLight** [weaviate/weaviate-python-client#1360]
When trying to run the python v4 client in python 3.10 and run this I get the following error:
```python 
import weaviate.classes as wvc
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/classes/__init__.py", line 1, in <module>
    from .config import ConsistencyLevel
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/classes/config.py", line 1, in <module>
    from weaviate.collections.classes.config import (
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/collections/__init__.py", line 1, in <module>
    from weaviate.collections.batch.collection import BatchCollection, CollectionBatchingContextManager
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/collections/batch/__init__.py", line 3, in <module>
    from .client import _BatchClient
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/collections/batch/client.py", line 3, in <module>
    from weaviate.collections.batch.base import (
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/collections/batch/base.py", line 16, in <module>
    from weaviate.cluster.types import Node
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/cluster/__init__.py", line 7, in <module>
    from .cluster import Cluster
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/cluster/cluster.py", line 10, in <module>
    from weaviate.connect import Connection
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/connect/__init__.py", line 7, in <module>
    from .v3 import Connection
  File "/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/connect/v3.py", line 20, in <module>
    from weaviate import __version__ as client_version
ImportError: cannot import name '__version__' from 'weaviate' (/home/lochy/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/weaviate/__init__.py)
```
```
Package                                 Version
--------------------------------------- -----------
grpcio | 1.67.0
grpcio-health-checking  | 1.67.0
grpcio-tools | 1.66.2
pip | 24.2
protobuf | 5.28.3
weaviate | 0.1.0
weaviate-client | 4.9.0
```

**Comment by dirkkul** [comment]
Hi

> weaviate | 0.1.0

can you remove this please and try again?

**Comment by PylotLight** [comment]
Successfully uninstalled weaviate-0.1.0...
Traceback (most recent call last):
  File "/home/lochy/repos/llm-tools/llm-tool-weaviate/demo.py", line 3, in <module>
    client = weaviate.connect_to_local(
AttributeError: module 'weaviate' has no attribute 'connect_to_local'

Still seem to having issues..

**Comment by dirkkul** [comment]
just to be sure, could you:

- create a new virtual environment
- install only weaviate-client in that env
- retry

**Comment by PylotLight** [comment]
I think that's working better.. 
Are we able to confirm what the conflict was? 
Is it asdf tool for managing python versions specifically, or just another globally installed module version conflict etc?

**Comment by dirkkul** [comment]
the `weaviate` is a dummy package and should not be installed - we are working on getting that resolved.

Thanks for confirming, will close this!
