### ISSUE TITLE
weaviate.__version__ returns 'unknown version'

### ISSUE THREAD

**Issue by anirudhpm** [weaviate/weaviate-python-client#306]
weaviate.__version__ is returning unknown version, **because of which weaviate-cli is not working as well**. it returns the following error.

```
Traceback (most recent call last):
  File "/home/poorani/.local/bin/weaviate", line 5, in <module>
    from cli import main
  File "/home/poorani/.local/lib/python3.9/site-packages/cli.py", line 5, in <module>
    from semi.commands.data import delete_all_data, import_data_from_file
  File "/home/poorani/.local/lib/python3.9/site-packages/semi/commands/data.py", line 5, in <module>
    VERSION_2 = (int(weaviate.__version__.split('.')[0]) < 3)
ValueError: invalid literal for int() with base 10: 'unknown version'
```

Note: this works fine with the older version(i tried 3.15.6)

**Comment by dirkkul** [comment]
we just released weaviate-cli 2.2.0 which should fix that problem
https://pypi.org/project/weaviate-cli/2.2.0/
