### ISSUE TITLE
support Windows as platform for embedded DB

### ISSUE THREAD

**Issue by jcovespi** [weaviate/weaviate-python-client#506]
Traceback (most recent call last):
...
  File "\venv\lib\site-packages\weaviate\embedded.py", line 52, in __init__
    self.check_supported_platform()
  File "\venv\lib\site-packages\weaviate\embedded.py", line 175, in check_supported_platform
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

**Comment by dirkkul** [comment]
please upvote this issue in the weaviate repo: https://github.com/weaviate/weaviate/issues/3315
