### ISSUE TITLE
GRPC fails vs Batch 

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate-python-client#692]
When using grpc uploading I get the below error.
I switched to using batching there was no issue. No idea if this is a client issue or a server issue - ie: maybe the client was trying to send too many objects at once? Unlikely. I didn't do a count but it was in the order of 1000 to 2000 nothing crazy (384d vector).

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weaviate\scrapeToWeaviate.py", line 343, in doTheUpload
    response = grpcer.data.insert_many(data_objects)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Local\Programs\Python\Python311\Lib\site-packages\weaviate\collections\data.py", line 352, in insert_many
    return self._batch_grpc.objects(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Local\Programs\Python\Python311\Lib\site-packages\weaviate\collections\batch\grpc.py", line 62, in objects
    weaviate_objs: List[batch_pb2.BatchObject] = [
                                                 ^
  File "Local\Programs\Python\Python311\Lib\site-packages\weaviate\collections\batch\grpc.py", line 72, in <listcomp>
    properties=self.__translate_properties_from_python_to_grpc(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Local\Programs\Python\Python311\Lib\site-packages\weaviate\collections\batch\grpc.py", line 188, in __translate_properties_from_python_to_grpc
    elif isinstance(val, list) and isinstance(val[0], dict):
                                              ~~~^^^
**IndexError: list index out of range**
```

**Comment by dirkkul** [comment]
Hi,

one of your objects has an empty list as a property which causes the error you are having. We are working on it and it should be fixed soonish (latest next week).

**Comment by msj121** [comment]
@dirkkul Thanks so much!
