### ISSUE TITLE
[Possible Bug] The client isn't parsing the `v1/node` endpoint data correctly (`stats` key missing)

### ISSUE THREAD

**Issue by databyjp** [weaviate/weaviate-python-client#896]
Reproducible on Weaviate 1.23.9/1.23.10 w Python client 4.4.4

Example:

```
import weaviate
import weaviate.classes.config as wc

client = weaviate.connect_to_local()

coll = client.collections.create(
    name="TempColl",
    properties=[wc.Property(name="title", data_type=wc.DataType.TEXT)],
    vectorizer_config=wc.Configure.Vectorizer.none()
)

coll.data.insert(
    properties={"title": "My Name Is"},
    vector=[0.1] * 100
)

print(client.cluster.nodes(collection=coll.name))

client.close()
```

```
Traceback (most recent call last):
  File "/Users/jphwang/code/weaviate-tutorials/python-int-workshop/bug_repro.py", line 17, in <module>
    print(client.cluster.nodes(collection=coll.name))
  File "/Users/jphwang/code/weaviate-tutorials/python-int-workshop/.venv/lib/python3.10/site-packages/weaviate/collections/cluster.py", line 84, in nodes
    else _ConvertFromREST.nodes_minimal(nodes)
  File "/Users/jphwang/code/weaviate-tutorials/python-int-workshop/.venv/lib/python3.10/site-packages/weaviate/collections/classes/cluster.py", line 69, in nodes_minimal
    return [
  File "/Users/jphwang/code/weaviate-tutorials/python-int-workshop/.venv/lib/python3.10/site-packages/weaviate/collections/classes/cluster.py", line 75, in <listcomp>
    object_count=node["stats"]["objectCount"],
KeyError: 'stats'
```

Actually, the data doesn't see to exist in the non-verbose `v1/nodes` endpoint.

```
{"nodes":[{"batchStats":{"queueLength":0,"ratePerSecond":0},"gitHash":"5a02ebb","name":"node1","shards":null,"status":"HEALTHY","version":"1.23.10"}]}
```

**Comment by dirkkul** [comment]
this should be fixed by https://github.com/weaviate/weaviate-python-client/pull/883

**Comment by databyjp** [comment]
Yup, confirmed :)
